name: Deploy Artifacts to Central

on:
  repository_dispatch:
    types: [ deploy_central ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "ARTIFACT_PATH=${{ github.event.client_payload.name }}-${{github.event.client_payload.version}}.tar.gz" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          repository: ${{ github.event.client_payload.github_repository }}
          run-id: ${{ github.event.client_payload.run_id }}
          github-token: ${{ secrets.GH_PAT }}
      - name: Verify Artifact Attestation
        run: gh attestation verify --repo ${{ github.event.client_payload.github_repository }} $ARTIFACT_PATH
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      - name: Untar the artifacts
        run: |
          tar -xzvf $ARTIFACT_PATH ./repository
          ls 
          tree repository
