name: Deploy Artifacts to Central
run-name: Deploy ${{ github.event.inputs.name }} ${{ github.event.inputs.version }} to Central
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the artifact'
        required: true
      version:
        description: 'Version of the artifact'
        required: true
      github_repository:
        description: 'GitHub repository of the artifact'
        required: true
      run_id:
        description: 'Run ID of the release workflow'
        required: true

permissions:
  contents: read

env:
  PAYLOAD_NAME: ${{ github.event.inputs.name }}
  PAYLOAD_VERSION: ${{ github.event.inputs.version }}
  PAYLOAD_REPOSITORY: ${{ github.event.inputs.github_repository }}
  PAYLOAD_RUN_ID: ${{ github.event.inputs.run_id }}

jobs:
  deploy_to_central:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ env.PAYLOAD_NAME }}-${{ env.PAYLOAD_VERSION }}.tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          repository: ${{ env.PAYLOAD_REPOSITORY }}
          run-id: ${{ env.PAYLOAD_RUN_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Artifact Attestation
        run: gh attestation verify --repo ${{ env.PAYLOAD_REPOSITORY }} $ARTIFACT_PATH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Untar the artifacts
        run: |
          mkdir repository
          tar -xzvf $ARTIFACT_PATH -C repository
      - name: Verify structure
        uses: jbangdev/jbang-action@v0.115.0
        with:
          script: validate_repository.java
        env:
          ARTIFACT_DIR: ./repository
          REPOSITORY: ${{ env.PAYLOAD_REPOSITORY }}
          NAME: ${{ env.PAYLOAD_NAME }}
          VERSION: ${{ env.PAYLOAD_VERSION }}

      - name: Deploy to Central
        run: echo Invoke the deployment script here
